### PR TITLE
Add Fan control with GPIO

### PR DESCRIPTION
**Pull request by casse-boubou**
Hello, first of all thank you very much for all your work!

#### Description
I added the possibility of controlling a fan via GPIO

I use your integration on my HomeAssistant on raspberry Pi4 to control the fan speed with PWM plugged into the GPIO ports.
But with your integration it appears as a light in the interface of my HomeAssistant.
I would like to be able to control it like a fan in my automations, my scripts and generally define it as a fan in HA since it is one.
This is why I based myself on your excellent work on the lights to add the possibility of defining a device connected to a GPIO port as a fan.
I managed to control my fan with the GPIO ports by following the explanations found on many different forums. This is why I think this new feature can be useful to many people who also use your integration to control a fan.
thanks again

#### Resume
Bug fix: no
New feature: yes
Fixed tickets: not for the moment

### CODE REVIEW

**Comment by RedMeKool** [comment]
Hey, I really like what you have done. I also use this addon purely to control the fan on my Raspberry Pi. I will test this first and merge if everything is working.

**Comment by RedMeKool** [comment]
```
Run python3 -m ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `.ruff.toml`:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
  - 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
  - 'mccabe' -> 'lint.mccabe'
custom_components/rpi_gpio_pwm/fan.py:125:35: F821 Undefined name `Optional`
custom_components/rpi_gpio_pwm/fan.py:125:70: F821 Undefined name `Optional`
custom_components/rpi_gpio_pwm/fan.py:125:102: F821 Undefined name `Any`
custom_components/rpi_gpio_pwm/fan.py:127:26: E7[11](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/actions/runs/8318497324/job/23076355629#step:5:12) Comparison to `None` should be `cond is not None`
custom_components/rpi_gpio_pwm/fan.py:[13](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/actions/runs/8318497324/job/23076355629#step:5:14)5:34: F8[21](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/actions/runs/8318497324/job/23076355629#step:5:22) Undefined name `Any`
Found 5 errors.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
Error: Process completed with exit code 1.
```

I get 5 errors in fan.py on 1 of the checks.
In lines 125,127 and 135 (Undefined name and Comparison to `None` should be `cond is not None`)
Could you have a look at that?

**Comment by casse-boubou** [comment]
> Could you have a look at that?

Yes it's okay
I don't know why, but it was the recommendations in the HA Doc regarding Fan entities.
https://developers.home-assistant.io/docs/core/entity/fan/
It's corrected and now the check passes

**Comment by RedMeKool** [comment]
@erdnaxela02  Well done!!! It is working perfectly on my setup. Really nice work 👍

**Pull request merged**
